- src/bivec.rs
- src/mat.rs
- src/vec.rs
- Adds slice/ptr accessors to BiVec
- Fixes all clippy warnings. It didn't like the transmutes, so they are changed to safe pointer casts now (removes unsafe as well).
- Fixed as_mut_ptr not borrowing the type mutably.
> Index accessors, clippy and safety fixes.

- src/geometry.rs
- src/int.rs
- src/mat.rs
- src/vec.rs
- Aabb volumes weren't `Copy`, even though they are just 2 Vec3s. Fixed.
- Added basic linear iterators to Aabb volumes. They iterator row-wise, and have configurable stride. `iter()` defaults to a stride of 1.
> Aabb need Copy trait + linear iterators of volumes

- src/mat.rs
- src/vec.rs
This allows for type safe, non-transmuting array referencing for various graphics APIs.
> Adds as_array and as_component_array where applicable to types

- src/vec.rs
- adds `refract : &mut self -> ()` method to types in the `vec` module
- changes `refracted` from `&mut self -> Self` to `&self -> Self`
> Add ’refract` and change `refracted` methods on `vec` types

- src/mat.rs
Not much to be said here. This is just a useful shorthand that lets you do this:
```rust
[
[1.0, 0.0, 0.0, 0.0],
[0.0, 1.0, 0.0, 0.0],
[0.0, 0.0, 0.5, 0.0],
[0.0, 0.0, 0.5, 1.0],
].into()
```
> Add From<[[T; 4]; 4]> implementation for Mat4.

- src/vec/vec4.rs
I was glancing through `vec4.rs` and saw something which looked a little bit like a copy-paste induced bug.
> Rename a couple of zs to ws in vec4.rs

- README.md
This is just a first shot at documenting the process of porting code without and with branches to wide data types with parallel processing.
It ended up being quite a bit longer than I initially expected so I don't think the `README.md` is the right place for it, but I wanted to make a PR to get your feedback on whether I have understood and documented things correctly as I did this while learning myself, whether you think this is useful or not, and how to proceed.
I tried to make the discussion accessible but in places I feel the language is still too complicated. And for the `blend` functions I was going to explain how to combine the logic up front, but it felt like it worked more naturally to try to do it by walking the scalar code path, getting stuck, and then trying something else. …
> README.md: Add examples for porting scalar code to wide data types

- src/mat.rs
I made a mistake that causes master to not compile when using the f64 feature. Here is a PR that fixes it. Sorry for the inconvenience
> Fix mat3 to rotor3

- src/bivec.rs
- src/int.rs
- src/interp.rs
- src/mat.rs
- src/vec/vec2.rs
- src/vec/vec3.rs
- src/vec/vec4.rs
Since `mul_add` only gets turned into FMA3 in haswell and up, and because typically FMA3 doesn't provide a lot of speedups even on newer machines, I've replaced a lot of calls to `mul_add`.
Similarly, rustc doesn't assume that FMA3 is available by default (it's quite pessimistic in it's world view) by default these calls end up in libc's fma which is quite a slowdown.
Was planning on doing these by regex but ran into a lot of issues, so this batch has manually replaced them.
> Remove `mul_add` calls in a lot of places

- src/mat.rs
I found this typo when looking at how the inversion of 3x3 matrices was implemented...
> Fix `Mat3::inverse`

- src/vec/vec2.rs
Made the docs on 2D wedge product a bit more beginner friendly, since the used function name comes from exterior algebra.
Althought mathematically correct, notations often used in physics and tutorials don't go into such detail.
> Reference cross product on 2D wedge product docs

- src/bivec.rs
- src/int.rs
- src/vec/vec2.rs
- src/vec/vec3.rs
- src/vec/vec4.rs
For VecN and DVecN, use Kahan summation algorithm to reduce float-point error.
This PR also corrects some indentation.
> Implement std::iter::Sum for Vec.

- src/bivec.rs
- src/impl_serde.rs
- src/rotor.rs
Here is a proposition to implement Issue #74 
Since, rotors and bivectors do not implement `PartialEq`, I addapted the methods from serde_test to write the unit tests for deserialization
> Implement serde traits for rotors and bivector

- CHANGELOG.md
- derivations/rotor2_rotate_vec_derivation.txt
- src/rotor.rs
This addresses #85. I saw that there was a fix in #86, but it seems more straightforward to do the simple fix per the derivation. A -1 factor was not distributed in the original derivation.
> Fix Rotor2::rotate_vec and corresponding derivation

- Cargo.toml
- src/lib.rs
- src/rotor.rs
Here is a proposition to implement #91 
I had to update `wide` to the latest version to be able to use `atan2` on wide types.
> Add Rotor3::into_angle_plane and update wide

- src/int.rs
The addition / fix (#97) is just a macro that gives the choice to implement the abs() method for an unsigned or signed integer vector. In theory an unsigned number does not require an abs() method but I added it for api consistency.
> Add & Fix: abs for IVecN and UVecN #97

- CHANGELOG.md
- src/transform.rs
This has the cool benefit of letting you [calculate the skinning ~~matrix~~ transform](https://github.com/KhronosGroup/glTF-Tutorials/blob/master/gltfTutorial/gltfTutorial_020_Skins.md#the-joint-matrices) for animations without having to convert from isometries/similarities at any point.
> Impl Mul<Scalar> and Add<Self> for isometries and similarities

- CHANGELOG.md
- src/impl_serde.rs
- src/lib.rs
- src/mat.rs
- deleted unused `use` statement
- changed `const XX: &'static [&'static str]` to  `const XX: &[& str]` as constants have by default a `'static` lifetime
- allow `into_isometry(&self)` explicitly where the convention would be to consume `self`
These are just some fixes for clippy, as clippy spamed my console when using my fork temporarily :)
> Fix some warnings for clippy

- src/rotor.rs
I remembered #93 and this is a small warning for undefined behaviour for antiparallel vectors.
> Better document undefined behavior in Rotor::from_rotation_between()

- CHANGELOG.md
- src/impl_serde.rs
I implemented the `impl_serde_vec!` for `f64` types as well and introduced new macros for matrices, implementing them as well. 
I needed it for my raytracer where I allow switching between `f32` and `f64` types.
**Further work may include (not in this PR)**
- Impl Serde for `DBivec` and `DRotor`
- Write tests for the new Serde implementations
> Impl Serde for DVec and DMat using macros

- src/int.rs
- src/vec/vec2.rs
- src/vec/vec3.rs
- src/vec/vec4.rs
Following simple changes were made:
- `impl From<>` rather than `impl Into<>` as it gives `into()` for free.
- Rename macros in `int.rs` to keep the rusty snake style and be coherent with the other crate-macros (like `ivec2s` instead of `IVec2`)
The previous macro name also "clashed" with the vector names themselves.
> Make clippy happy

- CHANGELOG.md
- src/conversion.rs
- src/int.rs
- src/lib.rs
- src/util.rs
- src/vec/vec2.rs
- src/vec/vec3.rs
- src/vec/vec4.rs
As conversions between vector types were not possible yet, I made some macros and made those possible. 
As `f32` to `i32`/`u32` may be problematic due to either one of those:
- `f32` is `NaN`, or
- `f32` is infinity or negative infinity, or
- `f32` is greater or less than the maximum/minimum of the target type
I implemented `TryFrom` to give a descriptive error in such cases. 
Implementing `TryFrom` is not possible for types out of the crate, so I used a module-private `TryFromExt` to circumvent it. 
In case of converting from float vectors to int vectors (like `Vec2` -> `IVec2`), any float precision will be lost, resulting in a lossy conversion that is practically "flooring" the float value to the next integer.
I wrote some simple tests for `Vec2` conversions, these could be extended but …
> impl TryFrom between vector types (#104)

- CHANGELOG.md
- src/int.rs
- src/vec/vec2.rs
- src/vec/vec3.rs
- src/vec/vec4.rs
This is useful in my case to remap indices in a `UVec3`, but seems generally useful to relax this bound, and matches what the standard library accepts for example in `array::map` or `Iterator::map`.
> Change bound in map/apply from Fn to FnMut

- src/impl_serde.rs
Fixes #138 by making matrices serialize as tuples, whereas previously they deserialized as tuples but serialized as sequences, breaking formats like `bincode` and `ron`. An alternative would be to make the deserializer expect a sequence. I chose to use `(de)serialize_tuple` because while `(de)serialize_seq` provides support for unknown-length sequences, we do not need this.
> Make matrix serialization and deserialization impls properly match.

- src/mat.rs
Fix `From<[[f32; 2]; 2]>` for `Mat2`
> fix 2d matrix from 2x2 array

- src/interp.rs
Fixes issue #152. As discussed in this issue and explained [here](https://github.com/KhronosGroup/glTF/issues/1395#issuecomment-933008176), most 3d engines (and model exporters) expect slerp between two quaternions (rotors in this case) to always take shortest path, despite dot product's sign.
Fixes an issue when interpolating between keyframes of animated models.
> Fix slurp not always taking shortest path

- src/mat.rs
This PR fixes #155 so that `Mat4::from_euler_angles` produces a rotation consistent with the `Mat4::from_rotation_*` functions when they are combined in the specified order (roll -> pitch -> yaw).
Also adds an additional test to verify the Mat4 rotations.
> Fix Mat4::from_euler_angles

- CHANGELOG.md
- Cargo.toml
- README.md
- src/interp.rs
- src/lib.rs
- src/vec/mod.rs
- src/vec/num_traits.rs
This is for #157.
* The `impl`s are in `src/vec/num_traits.rs`.
* This is behind a resp. feature flag documented in `src/lib.rs` and `README.md`.
* I took the liberty to reorder the features alphabetically (except `f64` & `int` as these are probably what people look for most).
* `clippy` clean.
I noticed three `serde` tests are failing when `cargo test --all-features` is ran but they did so before my changes:
```
test impl_serde::mat_serde_tests::mat2 ... FAILED
test impl_serde::mat_serde_tests::mat3 ... FAILED
test impl_serde::mat_serde_tests::mat4 ... FAILED
```
> Added support for `num_traits::identities`.

- CHANGELOG.md
- src/mat.rs
Hello again, this is a typo fix to make the output of `Mat4::as_mut_array` mutatable, to match the other matrix sizes.
If you have time to take a look for the next update then that would be awesome, thanks!
> Fix missing mut in Mat4::as_mut_array

- CHANGELOG.md
- src/impl_mint.rs
We're planning to use ultraviolet together with https://github.com/LPGhatguy/crevice (turns Rusty structs into structs that the GPU understands).
This adds more mint types to Ultraviolet, which will then make it possible to add really nice ultraviolet support to crevice.
> Add missing mint type conversions

- src/impl_mint.rs
This PR fixes a minor issue in #163 where `mint` conversions are added for integer types, but without checking that the `int` feature is enabled.
This leads to compile errors if `mint` is enabled without `int`.  With the changes in this PR, the two features can be enabled independently again (tested in a local project that only enables `mint`).
(No changelog entry since there has not yet been a release with these additional conversions.)
> Fix enabling mint without int

- CHANGELOG.md
- src/impl_mint.rs
This PR adds conversion between `mint::Quaternion` and `Rotor3` types, implemented using the existing functions `Rotor3::from_quaternion_array` and `Rotor3::into_quaternion_array`.
Tested locally in a project that uses `glam`, rotations seem to round-trip ok!  If this PR could be considered for a future update that would be great, thanks! :)
> Add mint quaternion support

- src/projection/lh_yup.rs
- src/projection/rh_yup.rs
This PR fixes only the `perspective_reversed_z_vk` functions and not the other projection matrix constructors.
I used Mathcad to simplify matrix definitions:
Further references I used are: 
- https://iolite-engine.com/blog_posts/reverse_z_cheatsheet
> Fix `perspective_reversed_z_vk` for `lh_yup` and `rh_yup`
