fu5ha/ultraviolet

CHANGELOG.md, Cargo.toml, docs/rotor2_rotate_rotor_derivation.txt, docs/rotor2_rotate_vec_derivation.txt, docs/rotor3_rotate_derivation.txt, docs/rotor3_rotate_rotor_derivation.txt, docs/rotor3_rotate_vec_derivation.txt, src/bivec.rs, src/lerp.rs, src/lib.rs, src/mat.rs, src/rotor.rs, src/util.rs, src/vec.rs
=> Bivectors and Rotors

src/mat.rs, src/vec.rs
- From/Into array types
- From/Into tuple types (for Vec only)
- as_slice/as_component_slice/as_byte_slice and as_ptr/as_mut_ptr derivatives for all types
=> This adds many convienence wrappers for:

src/geometry.rs, src/int.rs, src/lib.rs, src/mat.rs, src/vec.rs
- Adds unsigned integer vectors (vec2u, vec3u,vec4u). These had all floating-point specific operations removed.
- Adds geometric functions, only some basics for now. Plane and Rays for
intersection, and some basic Aabb volumes`
This also adds some various utility functions, mat4 translate, some Into implementations for arrays for Vecs, etc.
This isn't a complete set yet, it still needs signed versions of vectors and to flesh out the geometry. But this is enough to begin reviewing and merging it.
=> Integer vectors and some geometry

src/vec.rs
Fixes #39 
reference:  https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/refract.xhtml
=> Use refract algorithm from GLSL

Cargo.toml, src/lib.rs, src/mat.rs, src/vec.rs
Combined PartialEq changes from #31 and Serde changes from #25, enabled the tests and fixed some serde code in the process.
=> "rollup" of partialeq and serde

src/mat.rs
This for my personal use, I needed to interact with luminance, but it might be useful to other people too.
=> Added From<2dArray> for Mat[2,3,4]

src/bivec.rs
=> fix typo in bivec3 docs

src/mat.rs, src/vec/vec2.rs, src/vec/vec3.rs, src/vec/vec4.rs
Only eq needs to be implemented
=> Removes the PartialEq ne method impls

src/mat.rs
Here is a proposition to implement issue #61 
I made a separated `impl` block because I am not familiar with the strctures represented by `Mat3x4` or `Mat3x8`
Here is a code that can be used to test the correctness of the implementation
```
use rand::prelude::*;
use ultraviolet::*;
use std::f32::consts::FRAC_PI_2;
use std::f32::consts::PI;
fn main() {
for i in 0..=10 {
let alpha = (rand::random::<f32>() - 0.5) * std::f32::consts::PI;
let beta = (rand::random::<f32>() - 0.5) * std::f32::consts::PI;
let gamma = (rand::random::<f32>() - 0.5) * std::f32::consts::PI;
let rotor = Rotor3::from_euler_angles(alpha, beta, gamma);
let mat = rotor.into_matrix();
let rotor2 = mat.into_rotor3();
println!("test {}", i);
println!("{:?}", rotor);
println!("{:?}", rotor2); …
```
=> Add Mat3 to Rotor3 conversion

CHANGELOG.md, src/mat.rs
Here is an implementation of #79
=> Implement mat4 to isometry3 conversion

CHANGELOG.md, src/bivec.rs, src/mat.rs, src/rotor.rs, src/transform.rs, src/vec/vec2.rs, src/vec/vec3.rs, src/vec/vec4.rs
This means that SIMD variants and f64 variants also get PartialEq!
Fixes #82
=> Implement PartialEq in macros

src/bivec.rs
The reasoning is explained in #94
=> Fix Bivec3::from_normalized_axis

CHANGELOG.md, src/rotor.rs
=> Added quaternion convertion functions to Rotor3

CHANGELOG.md, src/impl_serde.rs
Here is an implementation of the serde traits for Isometry2 and Isometry3
=> Serde for isometry

CHANGELOG.md, src/int.rs
This does revert some weird `new` function stuff in the `IVec4`, but nobody was using that and it was inconsistent.
=> Added `const` to `new` functions for integer types.

src/int.rs
=> Make u/ivec abs pub again

CHANGELOG.md, src/mat.rs
Closes https://github.com/termhn/ultraviolet/issues/100. `truncate` works for me as long as it's documented well-enough.
=> Add Mat4::truncate()

src/mat.rs
=> Fix Mat3::from_euler_angle

CHANGELOG.md, src/rotor.rs
Here is a proposition for #105.
The proposed documentation may need to be reworded.
=> Add methods to scale Rotor3

CHANGELOG.md, src/int.rs
This solves #133 
This is my first PR so hopefully I did it right :)
cc @termhn
=> Impl Neg for IVecN

README.md, src/lib.rs
=> Update version in demo

CHANGELOG.md, src/impl_serde.rs
Exactly the same changes as in https://github.com/fu5ha/ultraviolet/pull/124.
Also fixed currently broken matrix tests, and added tests for Isometry (copy-pasted from existing code above).
~~*Still missing implementation for Similarity.*~~
=> Serde traits for the rest of f64 types
